Run RebuildTitleKeys as a db update maintenance script
DatabaseUpdater::$maintenance is protected since cd40724c5e8, hence we
can no more get it to runChild() the RebuildTitleKeys script that
generates the keys.

Causes:

Fatal error: Cannot access protected property MysqlUpdater::$maintenance
in extensions/TitleKey/TitleKey_body.php on line 148

Instead use addPostDatabaseUpdateMaintenance() to register the
maintenance script.

Bug: T163617
Change-Id: I152a2fd059b87cd0947b2ca40841c9daf9f84cb7